import json
import re
from typing import Tuple

from app.llm.ollama import OllamaClient
from app.agent.planner import PromptBuilder
from app.agent.context import context_manager
from app.applications.registry import tool_registry
from app.persona.deadpool import Persona
from app.safety.policy import safety_controller
from app.agent.intent_parser import intent_parser
from app.applications.discovery import app_discovery
from app.agent.state import StateMachine, AgentState
from app.agent.task import TaskState

class TaskController:
    def __init__(self):
        self.llm = OllamaClient()
        self.tools = tool_registry.get_schemas()
        self.system_prompt = PromptBuilder.build_system_prompt(self.tools)
        self.max_actions_per_task = 12
        self.debug_mode = False
        self.state_machine = StateMachine()
        
        # We can implement a callback or a queue for I/O instead of blocking input()
        self.io_callback = print
        self.io_request_input = input

    def toggle_debug(self, state: bool):
        self.debug_mode = state

    def debug_log(self, section: str, message: str):
        if self.debug_mode:
            print(f"\n[{section.upper()}]\n{message}\n")

    def _execute_tool_generic(self, task_state: TaskState, name: str, args: dict) -> str:
        risk = safety_controller.get_risk_level(name, args)
        if risk == safety_controller.DANGEROUS or risk == safety_controller.CONFIRM:
            self.state_machine.transition(AgentState.WAITING_PERMISSION)
            self.io_callback(f"\n⚠️ WARNING: Deadpool wants to execute a {risk} action: {name}({args})")
            confirm = self.io_request_input("Allow? (y/n): ").strip().lower()
            if confirm != 'y':
                self.io_callback("Action cancelled by user.")
                self.state_machine.transition(AgentState.EXECUTING)
                return f"Tool '{name}' execution was DENIED by the user for safety."
            
        self.state_machine.transition(AgentState.EXECUTING)
        self.io_callback(f"🔧 Executing {name}({args})...")
        
        # For intent parser mapping specific logic
        if name == "launch_application" and "app_name" in args:
            raw_app = args["app_name"]
            resolved = app_discovery.resolve_app(raw_app)
            if resolved and "ambiguous" not in resolved:
                args["app_name"] = resolved["executable"]
                task_state.active_application = resolved["id"]
        
        result = tool_registry.execute(name, args)
        return result

    def execute_intent_plan(self, task_state: TaskState, plan: dict) -> str:
        """Executes a plan generated by the fast-path intent parser using the standard tool executor."""
        results = []
        for step in plan["steps"]:
            action = step["action"]
            
            # Map legacy intent parser steps to actual tools
            tool_name = action
            args = {}
            if action == "open_app":
                tool_name = "launch_application"
                args = {"app_name": step["app"]}
            elif action == "type_text":
                tool_name = "type_text"
                args = {"text": step["text"]}
                if "target_app" in step:
                    self._execute_tool_generic(task_state, "focus_application", {"app_name": step["target_app"]})
            elif action == "open_url":
                tool_name = "open_url"
                args = {"url": step["url"]}
            elif action == "search":
                tool_name = "web_search"
                args = {"query": step["query"]}
                
            res = self._execute_tool_generic(task_state, tool_name, args)
            results.append(f"Tool '{tool_name}' returned: {res}")
            
        return "\n".join(results)

    def process_input(self, user_input: str) -> Tuple[str, str]:
        # Fast path intent parsing
        self.state_machine.transition(AgentState.UNDERSTANDING)
        intent_plan = intent_parser.parse_intent(user_input)
        
        if intent_plan:
            self.state_machine.transition(AgentState.PLANNING)
            task_state = TaskState(intent_plan["goal"])
            
            self.state_machine.transition(AgentState.EXECUTING)
            results = self.execute_intent_plan(task_state, intent_plan)
            
            self.state_machine.transition(AgentState.VERIFYING)
            self.state_machine.transition(AgentState.COMPLETED)
            msg = f"Done. Task executed successfully.\n{results}"
            self.state_machine.transition(AgentState.IDLE)
            return Persona.format_response("Done. " + intent_plan["goal"]), Persona.format_response("Done.")

        # Full LLM loop
        self.state_machine.transition(AgentState.OBSERVING)
        task_state = TaskState(user_input)
        
        try:
            active_window = tool_registry.execute("get_active_window", {})
            observation = f"User Request: {user_input}\nCurrent Active Window: {active_window}"
        except Exception:
            observation = user_input
            
        context_manager.add_message("user", observation)
        action_count = 0
        
        while action_count < self.max_actions_per_task:
            self.state_machine.transition(AgentState.PLANNING)
            action_count += 1
            prompt = PromptBuilder.build_user_prompt(user_input)
            
            full_response = ""
            for chunk in self.llm.generate(prompt, system=self.system_prompt, stream=False):
                full_response += chunk
                
            try:
                json_str = full_response
                if "```json" in full_response:
                    json_str = full_response.split("```json")[1].split("```")[0]
                elif "```" in full_response:
                    json_str = full_response.split("```")[1].split("```")[0]
                else:
                    match = re.search(r'(\{.*\})', full_response, re.DOTALL)
                    if match:
                        json_str = match.group(1)
                    else:
                        json_str = full_response.strip()
                        if not json_str.startswith("{") and '"text"' in json_str:
                            json_str = "{" + json_str
                        if not json_str.endswith("}"):
                            json_str = json_str + "}"
                    
                data = json.loads(json_str.strip())
                text = data.get("text", "")
                voice_text = data.get("voice_text", text)
                if not voice_text:
                    voice_text = text
                    
                tool_calls = data.get("tool_calls", [])
                if isinstance(tool_calls, dict):
                    tool_calls = [tool_calls]
                
                if not tool_calls:
                    self.state_machine.transition(AgentState.COMPLETED)
                    context_manager.add_message("assistant", text)
                    self.state_machine.transition(AgentState.IDLE)
                    return Persona.format_response(text), Persona.format_response(voice_text)
                    
                self.io_callback(f"\n[Deadpool is thinking...] {text}")
                
                tool_results = []
                for call in tool_calls:
                    name = call.get("name")
                    args = call.get("arguments", {})
                    result = self._execute_tool_generic(task_state, name, args)
                    tool_results.append(f"Tool '{name}' returned: {result}")
                
                self.state_machine.transition(AgentState.VERIFYING)
                user_input = "System Info (Tool Results):\n" + "\n".join(tool_results)
                context_manager.add_message("assistant", text + f" (Called: {[c.get('name') for c in tool_calls]})")
                
            except json.JSONDecodeError:
                self.state_machine.transition(AgentState.FAILED)
                msg = "I couldn't form a valid action plan. Let me try again or you can rephrase."
                context_manager.add_message("assistant", msg)
                self.state_machine.transition(AgentState.IDLE)
                return Persona.format_response(msg), Persona.format_response(msg)
                    
        self.state_machine.transition(AgentState.FAILED)
        msg = "I've been thinking for too long and hit my action limit! Let's try something else."
        formatted_response = Persona.format_response(msg)
        self.state_machine.transition(AgentState.IDLE)
        return formatted_response, formatted_response
